### ISSUE TITLE
Broken research chain

### ISSUE THREAD

**Issue by dnulho** [mexmer/ScienceCostTweakerM#10]
I just added SCT to my pack and started a fresh map. I have AAI, and after getting Electricity I should be able to research the t1 Lab. But I am not.

![electromagnetism lab unavailable](https://user-images.githubusercontent.com/5905416/43419815-e89c75a4-93f6-11e8-838f-57742b928e62.png)

Current Mod list:
[mod-list.txt](https://github.com/mexmer/ScienceCostTweakerM/files/2242621/mod-list.txt)
Let me know if there is any other info that you need, or anything else that I can do to help.

**Comment by mexmer** [comment]
Hmm, you can try to remove mods that affect research. And see if anything changes. When i was adding aai compatibility i was testing it with aai only, and also with aai + angels and bobs. With aai t1 lab should be rsearcheable in burner lab, no idea why is not. Will check on that later

**Comment by mexmer** [comment]
Btw. There should be two dependencies in tree, basic logistic and basic electricity. Can you check, if you have basic logistic tech? That one should add t0 undergroud belt and splitter i think

**Comment by dnulho** [comment]
Basic Logistics is behind electromagnetics research.
![basic logistics](https://user-images.githubusercontent.com/5905416/43421210-eb5f8890-93fa-11e8-96fb-58ec5611c5a3.png)

**Comment by dnulho** [comment]
I am using Bob's belt overhaul settings, it may make sense to do some kind of check to change basic logistics to t0 science if beltoverhaul = true and aai is present.

**Comment by mexmer** [comment]
hmm, guess it depends on mods load order, because both aai and bobs define basic logistic, and they override each other.

that is quite problem, but nothing i can fix. it needs to be fixed either on side of bob mods or aai.

well this is problem when people use nonprefixed names for items and technologies, they will conflict with each other.

if bobs loads after AAI you will have t1 tech basic logistic, if AAI loads after bobs, then you will have basic logistic at t0

you can lookup this code 
https://github.com/mexmer/ScienceCostTweakerM/blob/master/tweaks/aai/1_update.lua

i set basic logistic to t0 pack, and yes i have tested that with combination of bobs + angels + aai, but problem is same name and mod load order.

i will try to invent some fix for that, but bob and earendel still need to fix between themselves to not ovewrite each other.

**Comment by dnulho** [comment]
I added dependencies to AAI requiring bobslogistics, , and then to bobslogistics requiring aai, to force mod load order, but the issue is persisting in both configurations.

**Comment by dnulho** [comment]
I have also found that it looks like bob may have addressed the tech naming issue. The basic logistics tech n bobslogistics is called "bob-logistics-0".

**Comment by dnulho** [comment]
I found the issue: when "bobmods-logistics-beltoverhaul" = true, it hides "basic-logistics" and creates "bob-logistics-0" as a t1 research. "basic-logistics" is now unresearchable, as are all dependencies, in this case "sct-lab-t1". Possible solution: have a section in the bobs logistics that checks that flag and changes sct-lab-t1 to depend on "bob-logistics-0" instead of "basic-logistics".

**Comment by mexmer** [comment]
like i said, i will look into that later, but just FYI i tried to load AAI + BOB + ANGEL belt and inserter overhaul enabled and research is still correct, i believe some other mod is interfering with research.

when bob belt overhaul is in place lab requires gray belt instead of yellow one, so technically basic logistic from aai is not required, but works for me even with that dependency, i will add other mods from your setup to mine to see, when it breaks.

**Comment by dnulho** [comment]
Ok, I have found the offending mod: More Bobs https://mods.factorio.com/mod/morebobs

**Comment by dnulho** [comment]
https://github.com/GimoXagros/morebobs/issues/1 started an issue with morebobs. See where that goes.

**Comment by mexmer** [comment]
good work, i will still add removal of basic-logistic dependence, since that is nifty idea, my change will be somewhate simplier than your patch tho'. not sure when it will be released, i'm currently working on changing expensive recipes for labs, so i will include it with that  in few days.

anyways, thanks for your work, finding culprit of issue you reported 👍

**Comment by mexmer** [comment]
i did publish version, that has basic logistic removed from dependencies, when black belts are in.
