### ISSUE TITLE
Incorrect crafting time on science packs

### ISSUE THREAD

**Issue by minno726** [mexmer/ScienceCostTweakerM#3]
In version 0.16.17, most of the science packs are set to a crafting time of 0.5 seconds. This issue is not present in version 0.16.13. If I use version 0.16.17 but replace prototypes/recipes/sciencepacks.lua with the one from version 0.16.13, the problem goes away, so it looks like there's something going wrong in there.

I'm using this mod as part of the Sea Block mod pack with some mods (including this one) updated to the latest version.

**Comment by mexmer** [comment]
thanks, looks once again i fell to trap of incomplete factorio documentatio and samples.
seems when you specify normal and expensive recipe, energy_cost is ignored, it needs to be specified in respective variant of recipe, otherwise defaults to whatever is default value, neither documentation or sample show this.

will be fixed in next release
