### ISSUE TITLE
Excessive prerequisites added

### ISSUE THREAD

**Issue by KiwiHawk** [mexmer/ScienceCostTweakerM#54]
In a Sea Block game without SCT, there are only eight techs that have red science tech as a prerequisite. With SCT the number is increased to hundreds. Is this something we can fix? (I'm a dev on Sea Block).

![image](https://user-images.githubusercontent.com/59639/102875821-325c3e80-44a9-11eb-9c82-ead39427baa1.png)

I commented out line in ScienceCostTweakerM\prototypes\2_technology
--connect_sciencepack(nil, first_science)
and then it looks like this:

![image](https://user-images.githubusercontent.com/59639/102957058-5453d080-453e-11eb-804f-86f221890937.png)

Is there something you/I can do to make this work properly? It's not very user friendly as is.

**Comment by mexmer** [comment]
science pack connect can be disabled in mod settings, you don't need to comment that line out.

this function is feature (that's why it has settings) it defaults to true.

![image](https://user-images.githubusercontent.com/5429727/103213611-7ff40380-490e-11eb-8b6d-477408ef3d12.png)

instead of commenting out code, just set default 
```
sct-connect-science = false
```

i might it future change it so it will connect only to hightest pack, it was added to connect those technologies hanging in air starting from nothing (eg. technologies with 0 dependency).

**Comment by mexmer** [comment]
there was bug, that only happened for some mods with different SP normalization
